name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v4

      - name: list hello_world.txt file content
        run: echo "$(cat hello_world.txt)"

      - name: List all files before switching directory
        run: ls -a
        
      - name: switch to MyHome directory      
        run: cd MyHome

      - name: List all files after switching directory
        run: ls -a
        
      - name: Show me where I am 
        run: pwd
        
      - name: list text.txt contest
        run: echo "$(cat test.txt)"
