name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v4

      - name: list hello_world.txt file content
        run: echo "$(cat hello_world.txt)"
        
      - name: list text.txt contest
        run: echo "$(cat test.txt)"
        working-directory: MyHome
      
      - name: list text.txt contest again
        run: echo "$(cat test.txt)"
